var quizQuestions = [{'question': 'Ta Suisse investit ',
  'answers': [{'content': 'dans les pistes cyclable', 'type': 'x'},
   {'content': 'dans le rail', 'type': 'y'},
   {'content': 'dans les autoroutes à huit pistes', 'type': 'z'}]},
 {'question': 'Ta Suisse instaure',
  'answers': [{'content': 'une forte taxe sur le kérosène', 'type': 'x'},
   {'content': 'une essence détaxée', 'type': 'y'},
   {'content': 'une interdiction des véhicules à essence', 'type': 'z'}]},
 {'question': 'Ta Suisse favorise la mobilité',
  'answers': [{'content': 'combinée', 'type': 'x'},
   {'content': 'partagée', 'type': 'y'},
   {'content': 'individuelle', 'type': 'z'}]},
 {'question': 'Ta Suisse promeut ',
  'answers': [{'content': 'le zéro dechet', 'type': 'x'},
   {'content': 'le zéro tri', 'type': 'y'},
   {'content': 'cinq poubelles sur les balcons', 'type': 'z'}]},
 {'question': 'Ta Suisse vise',
  'answers': [{'content': 'la décroissance', 'type': 'x'},
   {'content': 'la croissance à deux chiffres', 'type': 'y'},
   {'content': 'la croissance contrôlée', 'type': 'z'}]},
 {'question': 'Ta Suisse se nourrit',
  'answers': [{'content': 'en autosuffisance nationale', 'type': 'x'},
   {'content': 'en proposant les mêmes produits importés', 'type': 'y'},
   {'content': 'en favorisant les circuits courts', 'type': 'z'}]},
 {'question': 'Ta Suisse se chauffe',
  'answers': [{'content': 'au chauffage collectif', 'type': 'x'},
   {'content': 'au chauffage individuel', 'type': 'y'},
   {'content': "Pas de chauffage, il fait 30 à l'année", 'type': 'z'}]},
 {'question': 'Ta Suisse construit ',
  'answers': [{'content': "des immeuble d'appartements", 'type': 'x'},
   {'content': "des gratte-ciel de centaines d'étages", 'type': 'y'},
   {'content': 'des villas individuelles', 'type': 'z'}]},
 {'question': 'Ta Suisse développe des logemenets',
  'answers': [{'content': 'énergétiquement autonomes', 'type': 'x'},
   {'content': 'au label minergique (isolation)', 'type': 'y'},
   {'content': "moins chers peu importe l'impact écologique", 'type': 'z'}]}];

export default quizQuestions;
